<?php
if (($monyxi_slider_sc = monyxi_get_theme_option('front_page_title_shortcode')) != '' && strpos($monyxi_slider_sc, '[')!==false && strpos($monyxi_slider_sc, ']')!==false) {

	?><div class="front_page_section front_page_section_title front_page_section_slider front_page_section_title_slider"><?php
		// Add anchor
		$monyxi_anchor_icon = monyxi_get_theme_option('front_page_title_anchor_icon');	
		$monyxi_anchor_text = monyxi_get_theme_option('front_page_title_anchor_text');	
		if ((!empty($monyxi_anchor_icon) || !empty($monyxi_anchor_text)) && shortcode_exists('trx_sc_anchor')) {
			echo do_shortcode('[trx_sc_anchor id="front_page_section_title"'
											. (!empty($monyxi_anchor_icon) ? ' icon="'.esc_attr($monyxi_anchor_icon).'"' : '')
											. (!empty($monyxi_anchor_text) ? ' title="'.esc_attr($monyxi_anchor_text).'"' : '')
											. ']');
		}
		// Show slider (or any other content, generated by shortcode)
		echo do_shortcode($monyxi_slider_sc);
	?></div><?php

} else {

	?><div class="front_page_section front_page_section_title<?php
				$monyxi_scheme = monyxi_get_theme_option('front_page_title_scheme');
				if (!monyxi_is_inherit($monyxi_scheme)) echo ' scheme_'.esc_attr($monyxi_scheme);
				echo ' front_page_section_paddings_'.esc_attr(monyxi_get_theme_option('front_page_title_paddings'));
			?>"<?php
			$monyxi_css = '';
			$monyxi_bg_image = monyxi_get_theme_option('front_page_title_bg_image');
			if (!empty($monyxi_bg_image)) 
				$monyxi_css .= 'background-image: url('.esc_url(monyxi_get_attachment_url($monyxi_bg_image)).');';
			if (!empty($monyxi_css))
				echo ' style="' . esc_attr($monyxi_css) . '"';
	?>><?php
		// Add anchor
		$monyxi_anchor_icon = monyxi_get_theme_option('front_page_title_anchor_icon');	
		$monyxi_anchor_text = monyxi_get_theme_option('front_page_title_anchor_text');	
		if ((!empty($monyxi_anchor_icon) || !empty($monyxi_anchor_text)) && shortcode_exists('trx_sc_anchor')) {
			echo do_shortcode('[trx_sc_anchor id="front_page_section_title"'
											. (!empty($monyxi_anchor_icon) ? ' icon="'.esc_attr($monyxi_anchor_icon).'"' : '')
											. (!empty($monyxi_anchor_text) ? ' title="'.esc_attr($monyxi_anchor_text).'"' : '')
											. ']');
		}
		?>
		<div class="front_page_section_inner front_page_section_title_inner<?php
			if (monyxi_get_theme_option('front_page_title_fullheight'))
				echo ' monyxi-full-height sc_layouts_flex sc_layouts_columns_middle';
			?>"<?php
				$monyxi_css = '';
				$monyxi_bg_mask = monyxi_get_theme_option('front_page_title_bg_mask');
				$monyxi_bg_color = monyxi_get_theme_option('front_page_title_bg_color');
				if (!empty($monyxi_bg_color) && $monyxi_bg_mask > 0)
					$monyxi_css .= 'background-color: '.esc_attr($monyxi_bg_mask==1
																		? $monyxi_bg_color
																		: monyxi_hex2rgba($monyxi_bg_color, $monyxi_bg_mask)
																	).';';
				if (!empty($monyxi_css))
					echo ' style="' . esc_attr($monyxi_css) . '"';
		?>>
			<div class="front_page_section_content_wrap front_page_section_title_content_wrap content_wrap">
				<?php
				// Caption
				$monyxi_caption = monyxi_get_theme_option('front_page_title_caption');
				if (!empty($monyxi_caption) || (current_user_can('edit_theme_options') && is_customize_preview())) {
					?><h1 class="front_page_section_caption front_page_section_title_caption front_page_block_<?php echo !empty($monyxi_caption) ? 'filled' : 'empty'; ?>"><?php echo wp_kses($monyxi_caption, 'monyxi_kses_content'); ?></h1><?php
				}
			
				// Description (text)
				$monyxi_description = monyxi_get_theme_option('front_page_title_description');
				if (!empty($monyxi_description) || (current_user_can('edit_theme_options') && is_customize_preview())) {
					?><div class="front_page_section_description front_page_section_title_description front_page_block_<?php echo !empty($monyxi_description) ? 'filled' : 'empty'; ?>"><?php echo wp_kses(wpautop($monyxi_description), 'monyxi_kses_content'); ?></div><?php
				}
				
				// Buttons
				if (monyxi_get_theme_option('front_page_title_button1_link')!='' || monyxi_get_theme_option('front_page_title_button2_link')!='') {
					?><div class="front_page_section_buttons front_page_section_title_buttons"><?php
						monyxi_show_layout(monyxi_customizer_partial_refresh_front_page_title_button1_link());
						monyxi_show_layout(monyxi_customizer_partial_refresh_front_page_title_button2_link());
					?></div><?php
				}
				?>
			</div>
		</div>
	</div>
	<?php
}